<?php
/**
 * Created Vlad Karapetyan
 */

require_once 'Client_OXD.php';
require_once 'Obtain_trait.php';

class Obtain_pat extends Client_oxd
{

    use Obtain_trait;
    /**start parameter for response!**/
        private $response_pat_token;
        private $response_pat_refresh_token;
    /**end response parameter**/

    public function __construct()
    {
        /**
         * Obtain_pat constructor.
         */
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getResponsePatToken()
    {
        $this->response_pat_token = $this->getResponseData()->pat_token;
        return $this->response_pat_token;
    }

    /**
     * @return mixed
     */
    public function getResponsePatRefreshToken()
    {
        $this->response_pat_refresh_token = $this->getResponseData()->pat_refresh_token;
        return $this->response_pat_refresh_token;
    }

    public function setCommand()
    {
        $this->command = 'obtain_pat';
    }
}