<?php
/**
 * Created by PhpStorm.
 * User: Vlad Karapetyan
 */
require_once 'Client_OXD.php';

class Access_token_status extends Client_oxd
{
    /**start parameter for request!**/
        private $req_discovery_url = null;
        private $req_id_token = null;
        private $req_access_token = null;
    /**end request parameter**/

    /**start parameter for response!**/
        public static $resp_active;
        public static $resp_expires_at;
        public static $resp_issued_at;
    /**end response parameter**/


    public function __construct()
    {
        /**
         * req_access_token_status constructor.
         **/
        parent::__construct(); // TODO: Change the autogenerated stub
    }
    /*
     * @param static
    */
    public function setRespParam(){
        self::$resp_active = $this->getRespData()->active;
        self::$resp_expires_at = $this->getRespData()->expires_at;
        self::$resp_issued_at = $this->getRespData()->issued_at;
    }

    /**
     * @return null
     */
    public function getReqDiscoveryUrl()
    {
        return $this->req_discovery_url;
    }

    /**
     * @param null $req_discovery_url
     */
    public function setReqDiscoveryUrl($req_discovery_url)
    {
        $this->req_discovery_url = $req_discovery_url;
    }

    /**
     * @return null
     */
    public function getReqIdToken()
    {
        return $this->req_id_token;
    }

    /**
     * @param null $req_id_token
     */
    public function setReqIdToken($req_id_token)
    {
        $this->req_id_token = $req_id_token;
    }

    /**
     * @return null
     */
    public function getReqAccessToken()
    {
        return $this->req_access_token;
    }

    /**
     * @param null $req_access_token
     */
    public function setReqAccessToken($req_access_token)
    {
        $this->req_access_token = $req_access_token;
    }

    public function setCommand()
    {
        $this->command = 'access_token_status';
    }

    public function setParams()
    {
        $this->params = array(
            "discovery_url" => $this->getReqDiscoveryUrl(),
            "id_token" => $this->getReqIdToken(),
            "access_token" => $this->getReqAccessToken()
        );
    }

}