<?php
/**
 * Created by PhpStorm.
 * User: Vlad Karapetyan
 */
require_once 'Client_OXD.php';

class Authorization_code_flow extends Client_oxd
{
    /**start parameter for request!**/
        private $req_discovery_url = null;
        private $req_redirect_url = null;
        private $req_client_id = null;
        private $req_client_secret = null;
        private $req_user_id = null;
        private $req_user_secret = null;
        private $req_scope = null;
        private $req_nonce = null;
        private $req_acr = null;
    /**end request parameter**/

    /**start parameter for response!**/
        public static $resp_access_token;
        public static $resp_expires_in_seconds;
        public static $resp_id_token;
        public static $resp_refresh_token;
        public static $resp_authorization_code;
        public static $resp_scope;
    /**end response parameter**/

    public function __construct()
    {
        /**
         * req_access_token_status constructor.
         **/
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getReqDiscoveryUrl()
    {
        return $this->req_discovery_url;
    }

    /**
     * @param mixed $req_discovery_url
     */
    public function setReqDiscoveryUrl($req_discovery_url)
    {
        $this->req_discovery_url = $req_discovery_url;
    }

    /**
     * @return null
     */
    public function getReqRedirectUrl()
    {
        return $this->req_redirect_url;
    }

    /**
     * @param null $req_redirect_url
     */
    public function setReqRedirectUrl($req_redirect_url)
    {
        $this->req_redirect_url = $req_redirect_url;
    }

    /**
     * @return null
     */
    public function getReqClientId()
    {
        return $this->req_client_id;
    }

    /**
     * @param null $req_client_id
     */
    public function setReqClientId($req_client_id)
    {
        $this->req_client_id = $req_client_id;
    }

    /**
     * @return null
     */
    public function getReqClientSecret()
    {
        return $this->req_client_secret;
    }

    /**
     * @param null $req_client_secret
     */
    public function setReqClientSecret($req_client_secret)
    {
        $this->req_client_secret = $req_client_secret;
    }

    /**
     * @return null
     */
    public function getReqUserId()
    {
        return $this->req_user_id;
    }

    /**
     * @param null $req_user_id
     */
    public function setReqUserId($req_user_id)
    {
        $this->req_user_id = $req_user_id;
    }

    /**
     * @return null
     */
    public function getReqUserSecret()
    {
        return $this->req_user_secret;
    }

    /**
     * @param null $req_user_secret
     */
    public function setReqUserSecret($req_user_secret)
    {
        $this->req_user_secret = $req_user_secret;
    }

    /**
     * @return null
     */
    public function getReqScope()
    {
        return $this->req_scope;
    }

    /**
     * @param null $req_scope
     */
    public function setReqScope($req_scope)
    {
        $this->req_scope = $req_scope;
    }

    /*
     * @return null
    */
    public function getReqNonce()
    {
        return $this->req_nonce;
    }

    /*
     * @param null $req_nonce
    */
    public function setReqNonce($req_nonce)
    {
        $this->req_nonce = $req_nonce;
    }

    /*
     * @return null
    */
    public function getReqAcr()
    {
        return $this->req_acr;
    }

    /*
     * @param null $req_acr
    */
    public function setReqAcr($req_acr)
    {
        $this->req_acr = $req_acr;
    }
    /*
     * @param static
    */
    public function setRespParam(){
        self::$resp_authorization_code = $this->getRespData()->authorization_code;
        self::$resp_scope = $this->getRespData()->scope;
        self::$resp_refresh_token = $this->getRespData()->refresh_token;
        self::$resp_id_token = $this->getRespData()->id_token;
        self::$resp_access_token = $this->getRespData()->access_token;
        self::$resp_expires_in_seconds = $this->getRespData()->expires_in_seconds;
    }

    public function setCommand()
    {
        $this->command = 'authorization_code_flow';
    }

    public function setParams()
    {
        $this->params = array(
            "discovery_url" => $this->getReqDiscoveryUrl(),
            "redirect_url" => $this->getReqRedirectUrl(),
            "client_id" => $this->getReqClientId(),
            "client_secret" => $this->getReqClientSecret(),
            "user_id" => $this->getReqUserId(),
            "user_secret" => $this->getReqUserSecret(),
            "scope" => $this->getReqScope(),
            "nonce" => $this->getReqNonce(),
            "acr" => $this->getReqAcr()
        );
    }

}