<?php

require_once 'Client_OXD.php';

class Authorize_rpt extends Client_oxd
{
    /**start parameter for request!**/
    private $request_aat_token = null;
    private $request_am_host = null;
    private $request_rpt_token = null;
    private $request_ticket = null;
    private $request_claims = null;

    /**end request parameter**/
    public function __construct()
    {
        /**
         * Authorize_rpt constructor.
         * @param $ip='127.0.0.1', $port=8099
         **/
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return null
     */
    public function getRequestAatToken()
    {
        return $this->request_aat_token;
    }

    /**
     * @param null $request_aat_token
     */
    public function setRequestAatToken($request_aat_token)
    {
        $this->request_aat_token = $request_aat_token;
    }

    /**
     * @return null
     */
    public function getRequestAmHost()
    {
        return $this->request_am_host;
    }

    /**
     * @param null $request_am_host
     */
    public function setRequestAmHost($request_am_host)
    {
        $this->request_am_host = $request_am_host;
    }

    /**
     * @return null
     */
    public function getRequestRptToken()
    {
        return $this->request_rpt_token;
    }

    /**
     * @param null $request_rpt_token
     */
    public function setRequestRptToken($request_rpt_token)
    {
        $this->request_rpt_token = $request_rpt_token;
    }

    /**
     * @return null
     */
    public function getRequestTicket()
    {
        return $this->request_ticket;
    }

    /**
     * @param null $request_ticket
     */
    public function setRequestTicket($request_ticket)
    {
        $this->request_ticket = $request_ticket;
    }

    /**
     * @return null
     */
    public function getRequestClaims()
    {
        return $this->request_claims;
    }

    /**
     * @param null $request_claims
     */
    public function setRequestClaims($request_claims)
    {
        $this->request_claims = $request_claims;
    }

    public function setCommand()
    {
        $this->command = 'authorize_rpt';
    }

    public function setParams()
    {
        $this->params = array(
            "aat_token" => $this->getRequestAatToken(),
            "rpt_token" => $this->getRequestRptToken(),
            "am_host" => $this->getRequestAmHost(),
            "ticket" => $this->getRequestTicket(),
            "claims" => $this->getRequestClaims()
        );
    }

}