<?php
/**
 * Created by PhpStorm.
 * User: Vlad Karapetyan
 */
require_once 'Client_OXD.php';

class Authorize_rpt extends Client_oxd
{
    /**start parameter for request!**/
        private $req_aat_token = null;
        private $req_am_host = null;
        private $req_rpt_token = null;
        private $req_ticket = null;
        private $req_claims = null;
    /**end request parameter**/

    public function __construct()
    {
        /**
         * Authorize_rpt constructor.
         **/
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return null
     */
    public function getReqAatToken()
    {
        return $this->req_aat_token;
    }

    /**
     * @param null $req_aat_token
     */
    public function setReqAatToken($req_aat_token)
    {
        $this->req_aat_token = $req_aat_token;
    }
    /*
     * @param static
    */
    public function setRespParam(){

    }
    /**
     * @return null
     */
    public function getReqAmHost()
    {
        return $this->req_am_host;
    }

    /**
     * @param null $req_am_host
     */
    public function setReqAmHost($req_am_host)
    {
        $this->req_am_host = $req_am_host;
    }

    /**
     * @return null
     */
    public function getReqRptToken()
    {
        return $this->req_rpt_token;
    }

    /**
     * @param null $req_rpt_token
     */
    public function setReqRptToken($req_rpt_token)
    {
        $this->req_rpt_token = $req_rpt_token;
    }

    /**
     * @return null
     */
    public function getReqTicket()
    {
        return $this->req_ticket;
    }

    /**
     * @param null $req_ticket
     */
    public function setReqTicket($req_ticket)
    {
        $this->req_ticket = $req_ticket;
    }

    /**
     * @return null
     */
    public function getReqClaims()
    {
        return $this->req_claims;
    }

    /**
     * @param null $req_claims
     */
    public function setReqClaims($req_claims)
    {
        $this->req_claims = $req_claims;
    }

    public function setCommand()
    {
        $this->command = 'authorize_rpt';
    }

    public function setParams()
    {
        $this->params = array(
            "aat_token" => $this->getReqAatToken(),
            "rpt_token" => $this->getReqRptToken(),
            "am_host" => $this->getReqAmHost(),
            "ticket" => $this->getReqTicket(),
            "claims" => $this->getReqClaims()
        );
    }

}