<?php
/**
 * Created by PhpStorm.
 * User: Vlad Karapetyan
 */
require_once 'Client_OXD.php';

class Client_read extends Client_oxd
{
    /**start parameter for request!**/
        private $req_registration_client_uri = null;
        private $req_registration_access_token = null;
    /**end request parameter**/

    /**start parameter for response!**/
        public static $resp_client_id;
        public static $resp_client_secret;
        public static $resp_registration_access_token;
        public static $resp_client_secret_expires_at;
        public static $resp_registration_client_uri;
        public static $resp_client_id_issued_at;
    /**end response parameter**/

    public function __construct()
    {
        /**
         * Client_read constructor.
         **/
        parent::__construct(); // TODO: Change the autogenerated stub
    }
    /*
     * @param static
    */
    public function setRespParam(){
        self::$resp_client_id = $this->getRespData()->client_id;
        self::$resp_client_secret = $this->getRespData()->client_secret;
        self::$resp_registration_access_token = $this->getRespData()->registration_access_token;
        self::$resp_client_secret_expires_at = $this->getRespData()->client_secret_expires_at;
        self::$resp_registration_client_uri = $this->getRespData()->registration_client_uri;
        self::$resp_client_id_issued_at = $this->getRespData()->client_id_issued_at;
    }
    /**
     * @return mixed
     */
    public function getReqRegistrationClientUri()
    {
        return $this->req_registration_client_uri;
    }

    /**
     * @param mixed $req_registration_client_uri
     */
    public function setReqRegistrationClientUri($req_registration_client_uri)
    {
        $this->req_registration_client_uri = $req_registration_client_uri;
    }

    /**
     * @return mixed
     */
    public function getReqRegistrationAccessToken()
    {
        return $this->req_registration_access_token;
    }

    /**
     * @param mixed $registration_access_token
     */
    public function setReqRegistrationAccessToken($req_registration_access_token)
    {
        $this->req_registration_access_token = $req_registration_access_token;
    }

    /**
     * @param mixed $command
     */
    public function setCommand()
    {
        $this->command = 'client_read';
    }

    /**
     * @return array
     */
    public function getParams()
    {
        return $this->params;
    }

    public function setParams()
    {
        $this->params = array(
            "registration_client_uri" => $this->getReqRegistrationClientUri(),
            "registration_access_token" => $this->getReqRegistrationAccessToken()
        );
    }
}
