<?php

class Client_read extends Client
{
    private $registration_client_uri = null;
    private $registration_access_token = null;


    public function __construct($protacol = 'tcp', $ip = '127.0.0.1', $port = 8099)
    {
        parent::__construct($protacol, $ip, $port); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getRegistrationClientUri()
    {
        return $this->registration_client_uri;
    }

    /**
     * @param mixed $registration_client_uri
     */
    public function setRegistrationClientUri($registration_client_uri)
    {
        $this->registration_client_uri = $registration_client_uri;
    }

    /**
     * @return mixed
     */
    public function getRegistrationAccessToken()
    {
        return $this->registration_access_token;
    }

    /**
     * @param mixed $registration_access_token
     */
    public function setRegistrationAccessToken($registration_access_token)
    {
        $this->registration_access_token = $registration_access_token;
    }
    /**
     * @param mixed $command
     */
    public function setCommand(){
        $this->command = 'client_read';
    }
    /**
     * @return array
     */
    public function getParams()
    {
        return $this->params;
    }
    public function setParams()
    {
      $this->params = array( "registration_client_uri"=>$this->getRegistrationClientUri(),
                             "registration_access_token"=>$this->getRegistrationAccessToken()
      );
    }

}