<?php
/**
 * Created by PhpStorm.
 * User: Vlad Karapetyan
 */
require_once 'Client_OXD.php';

class Get_authorization_url extends Client_oxd
{
    /**start parameter for request!**/
        private $req_oxd_id = null;
        private $req_acr_values = null;
    /**end request parameter**/

    /**start parameter for response!**/
        public static  $resp_authorization_url;
        public static  $resp_type;
        public static  $resp_client_id;
        public static  $resp_redirect_uri;
        public static  $resp_scope;
        public static  $resp_state;
        public static  $resp_nonce;
    /**end response parameter**/

    public function __construct()
    {
        /**
         * req_access_token_status constructor.
         **/
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->setReqAcrValues();
    }

    /**
     * @return mixed
     */
    public function getReqOxdId()
    {
        return $this->req_oxd_id;
    }

    /**
     * @param mixed $req_oxd_id
     */
    public function setReqOxdId($req_oxd_id)
    {
        $this->req_oxd_id = $req_oxd_id;
    }

    /**
     * @return null
     */
    public function getReqAcrValues()
    {
        return $this->req_acr_values;
    }

    /**
     * @param null $req_acr_values
     */
    public function setReqAcrValues($req_acr_values = ["basic", "duo"])
    {
        $this->req_acr_values = $req_acr_values;
    }
    /*
     * @param static
    */
    public function setRespParam(){
        self::$resp_authorization_url = $this->getRespData()->authorization_url;
        if($parts = parse_url(self::$resp_authorization_url)){
            parse_str($parts['query'], $query);
            self::$resp_type = $query['response_type'];
            self::$resp_client_id = $query['client_id'];
            self::$resp_redirect_uri = $query['redirect_uri'];
            self::$resp_scope = $query['scope'];
            self::$resp_state = $query['state'];
            self::$resp_nonce = $query['nonce'];
        }
    }
    public function setCommand()
    {
        $this->setReqAcrValues();
        $this->command = 'get_authorization_url';
    }

    public function setParams()
    {
        $this->params = array(
            "oxd_id" => $this->getReqOxdId(),
            "acr_values" => $this->getReqAcrValues()

        );
    }

}