<?php
/**
 * Created Vlad Karapetyan
 */

require_once 'Client_OXD.php';

class Get_authorization_code extends Client_oxd
{
    /**start parameter for request!**/
        private $request_oxd_id = null;
        private $request_acr_values = null;
        private $request_username = null;
        private $request_password = null;
    /**end request parameter**/

    /**start parameter for response!**/
        private $response_access_token;
    /**end response parameter**/

    public function __construct()
    {
        /**
         * request_access_token_status constructor.
         **/
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    public function getResponseAccessToken()
    {
        $this->response_access_token = $this->getResponseData()->access_token;
        return $this->response_access_token;
    }

    /**
     * @return null
     */
    public function getRequestPassword()
    {
        return $this->request_password;
    }

    /**
     * @param null $request_password
     */
    public function setRequestPassword($request_password)
    {
        $this->request_password = $request_password;
    }

    /**
     * @return mixed
     */
    public function getRequestOxdId()
    {
        return $this->request_oxd_id;
    }

    /**
     * @param mixed $request_oxd_id
     */
    public function setRequestOxdId($request_oxd_id)
    {
        $this->request_oxd_id = $request_oxd_id;
    }

    /**
     * @return null
     */
    public function getRequestAcrValues()
    {
        return $this->request_acr_values;
    }

    /**
     * @param null $request_acr_values
     */
    public function setRequestAcrValues($request_acr_values)
    {
        $this->request_acr_values = $request_acr_values;
    }

    /**
     * @return null
     */
    public function getRequestUsername()
    {
        return $this->request_username;
    }

    /**
     * @param null $request_username
     */
    public function setRequestUsername($request_username)
    {
        $this->request_username = $request_username;
    }

    /**
     * @param null $request_code
     */
    public function setCommand()
    {
        $this->command = 'get_authorization_code';
    }

    public function setParams()
    {
        $this->params = array(
            "oxd_id" => $this->getRequestOxdId(),
            "acr_values" => $this->getRequestAcrValues(),
            "username" => $this->getRequestUsername(),
            "password" => $this->getRequestPassword()
        );
    }

}