<?php

include 'Client.php';

class Get_user_info extends Client
{
    /**start parameter for request!**/
    private $request_oxd_id = null;
    private $request_access_token = null;
    /**end request parameter**/

    /**start parameter for response!**/
    private $response_sub;
    private $response_name;
    private $response_given_name;
    private $response_family_name;
    private $response_preferred_username;
    private $response_email;
    private $response_picture;
    /**end response parameter**/

    public function __construct()
    {
        /**
         * request_access_token_status constructor.
         * @param  $protacol='tcp', $ip='127.0.0.1', $port=8099
         **/
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return null
     */
    public function getRequestAccessToken()
    {
        return $this->request_access_token;
    }

    /**
     * @param null $request_access_token
     */
    public function setRequestAccessToken($request_access_token)
    {
        $this->request_access_token = $request_access_token;
    }

    /**
     * @return mixed
     */
    public function getRequestOxdId()
    {
        return $this->request_oxd_id;
    }

    /**
     * @param mixed $request_oxd_id
     */
    public function setRequestOxdId($request_oxd_id)
    {
        $this->request_oxd_id = $request_oxd_id;
    }

    /**
     * @return mixed
     */
    public function getResponseSub()
    {
        $this->response_sub = $this->getResponseData()->sub;
        return $this->response_sub;
    }

    /**
     * @return mixed
     */
    public function getResponseName()
    {
        $this->response_name = $this->getResponseData()->name;
        return $this->response_name;
    }

    /**
     * @return mixed
     */
    public function getResponseGivenName()
    {
        $this->response_given_name = $this->getResponseData()->given_name;
        return $this->response_given_name;
    }

    /**
     * @return mixed
     */
    public function getResponseFamilyName()
    {
        $this->response_family_name = $this->getResponseData()->family_name;
        return $this->response_family_name;
    }

    /**
     * @return mixed
     */
    public function getResponsePreferredUsername()
    {
        $this->response_preferred_username = $this->getResponseData()->preferred_username;
        return $this->response_preferred_username;
    }

    /**
     * @return mixed
     */
    public function getResponseEmail()
    {
        $this->response_email = $this->getResponseData()->email;
        return $this->response_email;
    }

    /**
     * @return mixed
     */
    public function getResponsePicture()
    {
        $this->response_picture = $this->getResponseData()->picture;
        return $this->response_picture;
    }

    public function setCommand(){
          $this->command = 'get_user_info';
    }

    public function setParams()
    {
          $this->params =  array( "oxd_id"=>$this->getRequestOxdId(),
                                  "access_token"=>$this->getRequestAccessToken()
          );
    }

}