<?php

include 'Client.php';

class Get_authorization_url extends Client
{
    /**start parameter for request!**/
    private $request_oxd_id = null;
    private $request_acr_values = null;
    /**end request parameter**/

    /**start parameter for response!**/
    private $response_authorization_url;
    /**end response parameter**/

    public function __construct()
    {
        /**
         * request_access_token_status constructor.
         * @param  $protacol='tcp', $ip='127.0.0.1', $port=8099
         **/
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getRequestOxdId()
    {
        return $this->request_oxd_id;
    }

    /**
     * @param mixed $request_oxd_id
     */
    public function setRequestOxdId($request_oxd_id)
    {
        $this->request_oxd_id = $request_oxd_id;
    }

    /**
     * @return null
     */
    public function getRequestAcrValues()
    {
        return $this->request_acr_values;
    }

    /**
     * @param null $request_acr_values
     */
    public function setRequestAcrValues($request_acr_values = 'basic')
    {
        $this->request_acr_values = $request_acr_values;
    }

    /**
     * @return mixed
     */
    public function getResponseAuthorizationUrl()
    {
        $this->response_authorization_url = $this->getResponseData()->authorization_url;
        return $this->response_authorization_url;
    }

    public function setCommand(){
        $this->setRequestAcrValues();
        $this->command = 'get_authorization_url';
    }

    public function setParams()
    {
          $this->params =  array( "oxd_id"=>$this->getRequestOxdId(),
                                  "acr_values"=>$this->getRequestAcrValues()

          );
    }

}