<?php
/**
 * Created by PhpStorm.
 * User: Vlad Karapetyan
 */
require_once 'Client_OXD.php';

class Get_user_info extends Client_oxd
{
    /**start parameter for request!**/
        private $req_oxd_id = null;
        private $req_access_token = null;
    /**end request parameter**/

    /**start parameter for response!**/
        public static $resp_claims;
        public static $resp_sub;
        public static $resp_name;
        public static $resp_given_name;
        public static $resp_family_name;
        public static $resp_preferred_username;
        public static $resp_email;
        public static $resp_picture;
    /**end response parameter**/

    public function __construct()
    {
        /**
         * req_access_token_status constructor.
         **/
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return null
     */
    public function getReqAccessToken()
    {
        return $this->req_access_token;
    }

    /**
     * @param null $req_access_token
     */
    public function setReqAccessToken($req_access_token)
    {
        $this->req_access_token = $req_access_token;
    }

    /**
     * @return mixed
     */
    public function getReqOxdId()
    {
        return $this->req_oxd_id;
    }

    /**
     * @param mixed $req_oxd_id
     */
    public function setReqOxdId($req_oxd_id)
    {
        $this->req_oxd_id = $req_oxd_id;
    }
    /*
     * @param static
    */
    public function setRespParam(){
        self::$resp_claims = $this->getRespData()->claims;
        self::$resp_sub = self::$resp_claims->sub;
        self::$resp_name = self::$resp_claims->name;
        self::$resp_given_name = self::$resp_claims->given_name;
        self::$resp_family_name = self::$resp_claims->family_name;
        self::$resp_preferred_username = self::$resp_claims->preferred_username;
        self::$resp_email = self::$resp_claims->email;
        self::$resp_picture = self::$resp_claims->picture;
    }

    public function setCommand()
    {
        $this->command = 'get_user_info';
    }

    public function setParams()
    {
        $this->params = array(
            "oxd_id" => $this->getReqOxdId(),
            "access_token" => $this->getReqAccessToken()
        );
    }

}