<?php
/**
 * Created by PhpStorm.
 * User: Vlad Karapetyan
 */
require_once 'Client_OXD.php';

class Get_authorization_code extends Client_oxd
{
    /**start parameter for request!**/
        private $req_oxd_id = null;
        private $req_acr_values = null;
        private $req_username = null;
        private $req_password = null;
    /**end request parameter**/

    /**start parameter for response!**/
        public static  $resp_access_token;
    /**end response parameter**/

    public function __construct()
    {
        /**
         * req_access_token_status constructor.
         **/
        parent::__construct(); // TODO: Change the autogenerated stub
    }
    /*
     * @param static
    */
    public function setRespParam(){
        self::$resp_access_token = $this->getRespData()->access_token;
    }
    /**
     * @return null
     */
    public function getReqPassword()
    {
        return $this->req_password;
    }

    /**
     * @param null $req_password
     */
    public function setReqPassword($req_password)
    {
        $this->req_password = $req_password;
    }

    /**
     * @return mixed
     */
    public function getReqOxdId()
    {
        return $this->req_oxd_id;
    }

    /**
     * @param mixed $req_oxd_id
     */
    public function setReqOxdId($req_oxd_id)
    {
        $this->req_oxd_id = $req_oxd_id;
    }

    /**
     * @return null
     */
    public function getReqAcrValues()
    {
        return $this->req_acr_values;
    }

    /**
     * @param null $req_acr_values
     */
    public function setReqAcrValues($req_acr_values)
    {
        $this->req_acr_values = $req_acr_values;
    }

    /**
     * @return null
     */
    public function getReqUsername()
    {
        return $this->req_username;
    }

    /**
     * @param null $req_username
     */
    public function setReqUsername($req_username)
    {
        $this->req_username = $req_username;
    }

    /**
     * @param null $req_code
     */
    public function setCommand()
    {
        $this->command = 'get_authorization_code';
    }

    public function setParams()
    {
        $this->params = array(
            "oxd_id" => $this->getReqOxdId(),
            "acr_values" => $this->getReqAcrValues(),
            "username" => $this->getReqUsername(),
            "password" => $this->getReqPassword()
        );
    }

}