<?php
/**
 * Created by PhpStorm.
 * User: Vlad Karapetyan
 */
require_once 'Client_OXD.php';

class Get_tokens_by_code extends Client_oxd
{
    /**start parameter for request!**/
        private $req_oxd_id = null;
        private $req_code = null;
        private $req_state = null;
        private $req_scopes = null;
    /**end request parameter**/

    /**start parameter for response!**/
        public static $resp_access_token;
        public static $resp_expires_in;
        public static $resp_id_token;
        public static $resp_id_token_claims;
    /**end response parameter**/

    public function __construct()
    {
        /**
         * req_access_token_status constructor.
         **/
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return null
     */
    public function getReqScopes()
    {
        return $this->req_scopes;
    }

    /**
     * @param null $req_scopes
     */
    public function setReqScopes($req_scopes)
    {
        $this->req_scopes = $req_scopes;
    }

    /**
     * @return mixed
     */
    public function getReqOxdId()
    {
        return $this->req_oxd_id;
    }

    /**
     * @param mixed $req_oxd_id
     */
    public function setReqOxdId($req_oxd_id)
    {
        $this->req_oxd_id = $req_oxd_id;
    }

    /**
     * @return null
     */
    public function getReqState()
    {
        return $this->req_state;
    }

    /**
     * @param null $req_state
     */
    public function setReqState($req_state)
    {
        $this->req_state = $req_state;
    }

    /**
     * @return null
     */
    public function getReqCode()
    {
        return $this->req_code;
    }

    /**
     * @param null $req_code
     */
    public function setReqCode($req_code)
    {
        $this->req_code = $req_code;
    }
    /*
     * @param static
    */
    public function setRespParam(){
        self::$resp_access_token = $this->getRespData()->access_token;
        self::$resp_expires_in = $this->getRespData()->expires_in;
        self::$resp_id_token = $this->getRespData()->id_token;
        self::$resp_id_token_claims = $this->getRespData()->id_token_claims;
    }

    public function setCommand()
    {
        $this->command = 'get_tokens_by_code';
    }

    public function setParams()
    {
        $this->params = array(
            "oxd_id" => $this->getReqOxdId(),
            "code" => $this->getReqCode(),
            "state" => $this->getReqState()
        );
    }

}