<?php

class Id_token_status extends Client
{
    private $discovery_url = null;
    private $id_token = null;

    /**
     * Id_token_status constructor.
     * @param $protacol='tcp', $ip='127.0.0.1', $port=8099
    **/
    public function __construct($protacol, $ip, $port)
    {
          parent::__construct($protacol, $ip, $port); // TODO: Change the autogenerated stub
    }

    /**
     * @return null
     */
    public function getDiscoveryUrl()
    {
        return $this->discovery_url;
    }

    /**
     * @param null $discovery_url
     */
    public function setDiscoveryUrl($discovery_url)
    {
        $this->discovery_url = $discovery_url;
    }

    /**
     * @return null
     */
    public function getIdToken()
    {
        return $this->id_token;
    }

    /**
     * @param null $id_token
     */
    public function setIdToken($id_token)
    {
        $this->id_token = $id_token;
    }


    public function setCommand(){
          $this->command = 'id_token_status';
    }
    public function setParams()
    {
          $this->params =  array( "discovery_url"=>$this->getDiscoveryUrl(),
                                  "id_token"=>$this->getIdToken()
          );
    }

}