<?php

include 'Client.php';

class Id_token_status extends Client
{
    /**start parameter for request!**/
    private $request_discovery_url = null;
    private $request_id_token = null;
    /**end request parameter**/

    /**start parameter for response!**/
    private $response_active;
    private $response_expires_at;
    private $response_issued_at;
    private $response_claims;
    /**end response parameter**/

    public function __construct()
    {
        /**
         * Id_token_status constructor.
         * @param $protacol='tcp', $ip='127.0.0.1', $port=8099
        **/
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getResponseActive()
    {
        $this->response_active = $this->getResponseData()->active;
        return $this->response_active;
    }

    /**
     * @return mixed
     */
    public function getResponseExpiresAt()
    {
        $this->response_expires_at = $this->getResponseData()->expires_at;
        return $this->response_expires_at;
    }

    /**
     * @return mixed
     */
    public function getResponseIssuedAt()
    {
        $this->response_issued_at = $this->getResponseData()->issued_at;
        return $this->response_issued_at;
    }

    /**
     * @return mixed
     */
    public function getResponseClaims()
    {
        $this->response_claims = $this->getResponseData()->claims;
        return $this->response_claims;
    }

    /**
     * @return null
     */
    public function getRequestDiscoveryUrl()
    {
        return $this->request_discovery_url;
    }

    /**
     * @param null $discovery_url
     */
    public function setRequestDiscoveryUrl($request_discovery_url)
    {
        $this->request_discovery_url = $request_discovery_url;
    }

    /**
     * @return null
     */
    public function getRequestIdToken()
    {
        return $this->request_id_token;
    }

    /**
     * @param null $id_token
     */
    public function setRequestIdToken($request_id_token)
    {
        $this->request_id_token = $request_id_token;
    }


    public function setCommand(){
          $this->command = 'id_token_status';
    }
    public function setParams()
    {
          $this->params =  array( "discovery_url"=>$this->getRequestDiscoveryUrl(),
                                  "id_token"=>$this->getRequestIdToken()
          );
    }

}