<?php
/**
 * Created by PhpStorm.
 * User: Vlad Karapetyan
 */
require_once 'Client_OXD.php';

class Id_token_status extends Client_oxd
{
    /**start parameter for request!**/
        private $req_discovery_url = null;
        private $req_id_token = null;
    /**end request parameter**/

    /**start parameter for response!**/
        public static $resp_active;
        public static $resp_expires_at;
        public static $resp_issued_at;
        public static $resp_claims;
    /**end response parameter**/

    public function __construct()
    {
        /**
         * Id_token_status constructor.
         **/
        parent::__construct(); // TODO: Change the autogenerated stub
    }
    /*
     * @param static
    */
    public function setRespParam(){
        self::$resp_active = $this->getRespData()->active;
        self::$resp_expires_at = $this->getRespData()->expires_at;
        self::$resp_issued_at = $this->getRespData()->issued_at;
        self::$resp_claims = $this->getRespData()->claims;
    }
    /**
     * @return null
     */
    public function getReqDiscoveryUrl()
    {
        return $this->req_discovery_url;
    }

    /**
     * @param null $discovery_url
     */
    public function setReqDiscoveryUrl($req_discovery_url)
    {
        $this->req_discovery_url = $req_discovery_url;
    }

    /**
     * @return null
     */
    public function getReqIdToken()
    {
        return $this->req_id_token;
    }

    /**
     * @param null $id_token
     */
    public function setReqIdToken($req_id_token)
    {
        $this->req_id_token = $req_id_token;
    }


    public function setCommand()
    {
        $this->command = 'id_token_status';
    }

    public function setParams()
    {
        $this->params = array(
            "discovery_url" => $this->getReqDiscoveryUrl(),
            "id_token" => $this->getReqIdToken()
        );
    }

}