<?php
/**
 * Created by PhpStorm.
 * User: Vlad Karapetyan
 */
require_once 'Client_OXD.php';
require_once 'Obtain_trait.php';

class Obtain_pat extends Client_oxd
{

    use Obtain_trait;
    /**start parameter for response!**/
    public static $resp_pat_token;
    public static $resp_pat_refresh_token;
    public static $resp_expires_in_seconds;
    public static $resp_authorization_code;
    public static $resp_scope;
    /**end response parameter**/


    public function __construct()
    {
        /**
         * Obtain_pat constructor.
         */
        parent::__construct(); // TODO: Change the autogenerated stub
    }
    /*
     * @param static
    */
    public function setRespParam(){
        self::$resp_pat_token = $this->getRespData()->pat_token;
        self::$resp_pat_refresh_token = $this->getRespData()->pat_refresh_token;
        self::$resp_expires_in_seconds = $this->getRespData()->expires_in_seconds;
        self::$resp_authorization_code = $this->getRespData()->authorization_code;
        self::$resp_scope = $this->getRespData()->scope;
    }
    public function setCommand()
    {
        $this->command = 'obtain_pat';
    }
}