<?php

include 'Client.php';
include 'Obtain_trait.php';
class Obtain_aat extends Client
{
    use Obtain_trait;
    /**start parameter for response!**/
    private $response_aat_token;
    private $response_aat_refresh_token;
    /**end response parameter**/


    public function __construct()
    {
        /**
         * Obtain_aat constructor.
         * @param $protacol='tcp', $ip='127.0.0.1', $port=8099
        */
        parent::__construct(); // TODO: Change the autogenerated stub
    }
    public function getRequestDiscoveryUrl()
    {
        return $this->request_discovery_url;
    }

    /**
     * @return mixed
     */
    public function getResponseAatToken()
    {
        $this->response_aat_token = $this->getResponseData()->aat_token;
        return $this->response_aat_token;
    }

    /**
     * @return mixed
     */
    public function getResponseAatRefreshToken()
    {
        $this->response_aat_refresh_token = $this->getResponseData()->aat_refresh_token;
        return $this->response_aat_refresh_token;
    }
    public function setCommand(){
        $this->command = 'obtain_aat';
    }
}
