<?php
/**
 * Created Vlad Karapetyan
 */

require_once 'Client_OXD.php';
require_once 'Obtain_trait.php';

class Obtain_aat extends Client_oxd
{
    use Obtain_trait;
    /**start parameter for response!**/
        private $response_aat_token;
        private $response_aat_refresh_token;
    /**end response parameter**/


    public function __construct()
    {
        /**
         * Obtain_aat constructor.
         */
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    public function getRequestDiscoveryUrl()
    {
        return $this->request_discovery_url;
    }

    /**
     * @return mixed
     */
    public function getResponseAatToken()
    {
        $this->response_aat_token = $this->getResponseData()->aat_token;
        return $this->response_aat_token;
    }

    /**
     * @return mixed
     */
    public function getResponseAatRefreshToken()
    {
        $this->response_aat_refresh_token = $this->getResponseData()->aat_refresh_token;
        return $this->response_aat_refresh_token;
    }

    public function setCommand()
    {
        $this->command = 'obtain_aat';
    }
}
