<?php

require_once 'Client_OXD.php';

class Obtain_rpt extends Client_oxd
{
    /**start parameter for request!**/
    private $request_aat_token = null;
    private $request_am_host = null;
    /**end request parameter**/

    /**start parameter for response!**/
    private $response_rpt_token;

    /**end response parameter**/

    public function __construct()
    {
        /**
         * Obtain_rpt constructor.
         * @param $ip='127.0.0.1', $port=8099
         **/
        parent::__construct(); // TODO: Change the autogenerated stub

    }

    /**
     * @return null
     */
    public function getRequestAatToken()
    {
        return $this->request_aat_token;
    }

    /**
     * @return mixed
     */
    public function getResponseRptToken()
    {
        $this->response_rpt_token = $this->getResponseData()->rpt_token;
        return $this->response_rpt_token;
    }

    /**
     * @param null $request_aat_token
     */
    public function setRequestAatToken($request_aat_token)
    {
        $this->request_aat_token = $request_aat_token;
    }

    /**
     * @return null
     */
    public function getRequestAmHost()
    {
        return $this->request_am_host;
    }

    /**
     * @param null $request_am_host
     */
    public function setRequestAmHost($request_am_host)
    {
        $this->request_am_host = $request_am_host;
    }

    public function setCommand()
    {
        $this->command = 'obtain_rpt';
    }

    public function setParams()
    {
        $this->params = array(
            "aat_token" => $this->getRequestAatToken(),
            "am_host" => $this->getRequestAmHost()
        );
    }
}
