<?php

include 'Client.php';
include 'Obtain_trait.php';
class Obtain_pat extends Client
{

    use Obtain_trait;
    /**start parameter for response!**/
    private $response_pat_token;
    private $response_pat_refresh_token;
    /**end response parameter**/


    public function __construct()
    {
        /**
         * Obtain_pat constructor.
         * @param $protacol='tcp', $ip='127.0.0.1', $port=8099
        */
        parent::__construct(); // TODO: Change the autogenerated stub
    }
    /**
     * @return mixed
     */
    public function getResponsePatToken()
    {
        $this->response_pat_token = $this->getResponseData()->pat_token;
        return $this->response_pat_token;
    }
    /**
     * @return mixed
     */
    public function getResponsePatRefreshToken()
    {
        $this->response_pat_refresh_token = $this->getResponseData()->pat_refresh_token;
        return $this->response_pat_refresh_token;
    }
    public function setCommand(){
        $this->command = 'obtain_pat';
    }
    public function setParams()
    {
          $this->params =  array( "discovery_url"=>$this->getRequestDiscoveryUrl(),
                                  "uma_discovery_url"=>$this->getRequestUmaDiscoveryUrl(),
                                  "redirect_url"=>$this->getRequestRedirectUrl(),
                                  "client_id"=>$this->getRequestClientId(),
                                  "client_secret"=>$this->getRequestClientSecret(),
                                  "user_id"=>$this->getRequestUserId(),
                                  "user_secret"=>$this->getRequestUserSecret()
          );
    }

}