<?php

class Obtain_rpt extends Client
{
    private $aat_token = null;
    private $am_host = null;

    /**
     * Obtain_rpt constructor.
     * @param $protacol='tcp', $ip='127.0.0.1', $port=8099
    **/
    public function __construct($protacol, $ip, $port)
    {
          parent::__construct($protacol, $ip, $port); // TODO: Change the autogenerated stub
    }

    /**
     * @return null
     */
    public function getAatToken()
    {
        return $this->aat_token;
    }

    /**
     * @param null $aat_token
     */
    public function setAatToken($aat_token)
    {
        $this->aat_token = $aat_token;
    }

    /**
     * @return null
     */
    public function getAmHost()
    {
        return $this->am_host;
    }

    /**
     * @param null $am_host
     */
    public function setAmHost($am_host)
    {
        $this->am_host = $am_host;
    }

    public function setCommand(){
          $this->command = 'obtain_rpt';
    }
    public function setParams()
    {
          $this->params =  array( "aat_token"=>$this->getAatToken(),
                                  "am_host"=>$this->getAmHost()
          );
    }

}