<?php
/**
 * Created by PhpStorm.
 * User: Vlad Karapetyan
 */
require_once 'Client_OXD.php';

class Obtain_rpt extends Client_oxd
{
    /**start parameter for request!**/
        private $req_aat_token = null;
        private $req_am_host = null;
    /**end request parameter**/

    /**start parameter for response!**/
        public static $resp_rpt_token;
    /**end response parameter**/

    public function __construct()
    {
        /**
         * Obtain_rpt constructor.
         **/
        parent::__construct(); // TODO: Change the autogenerated stub

    }

    /**
     * @return null
     */
    public function getReqAatToken()
    {
        return $this->req_aat_token;
    }
    /*
     * @param static
    */
    public function setRespParam()
    {
        self::$resp_rpt_token = $this->getRespData()->rpt_token;
    }

    /**
     * @param null $req_aat_token
     */
    public function setReqAatToken($req_aat_token)
    {
        $this->req_aat_token = $req_aat_token;
    }

    /**
     * @return null
     */
    public function getReqAmHost()
    {
        return $this->req_am_host;
    }

    /**
     * @param null $req_am_host
     */
    public function setReqAmHost($req_am_host)
    {
        $this->req_am_host = $req_am_host;
    }

    public function setCommand()
    {
        $this->command = 'obtain_rpt';
    }

    public function setParams()
    {
        $this->params = array(
            "aat_token" => $this->getReqAatToken(),
            "am_host" => $this->getReqAmHost()
        );
    }
}
