<?php

class Obtain_pat extends Client
{
    private $discovery_url = null;
    private $uma_discovery_url = null;
    private $redirect_url = null;
    private $client_id = null;
    private $client_secret = null;
    private $user_id = null;
    private $user_secret = null;

    /**
     * Obtain_pat constructor.
     * @param $protacol='tcp', $ip='127.0.0.1', $port=8099
     */
    public function __construct($protacol = 'tcp', $ip = '127.0.0.1', $port = 8099)
    {
        parent::__construct($protacol, $ip, $port); // TODO: Change the autogenerated stub
    }

    /**
     * @return null
     */
    public function getDiscoveryUrl()
    {
        return $this->discovery_url;
    }

    /**
     * @param null $discovery_url
     */
    public function setDiscoveryUrl($discovery_url)
    {
        $this->discovery_url = $discovery_url;
    }

    /**
     * @return null
     */
    public function getUmaDiscoveryUrl()
    {
        return $this->uma_discovery_url;
    }

    /**
     * @param null $uma_discovery_url
     */
    public function setUmaDiscoveryUrl($uma_discovery_url)
    {
        $this->uma_discovery_url = $uma_discovery_url;
    }

    /**
     * @return null
     */
    public function getRedirectUrl()
    {
        return $this->redirect_url;
    }

    /**
     * @param null $redirect_url
     */
    public function setRedirectUrl($redirect_url)
    {
        $this->redirect_url = $redirect_url;
    }

    /**
     * @return null
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * @param null $client_id
     */
    public function setClientId($client_id)
    {
        $this->client_id = $client_id;
    }

    /**
     * @return null
     */
    public function getClientSecret()
    {
        return $this->client_secret;
    }

    /**
     * @param null $client_secret
     */
    public function setClientSecret($client_secret)
    {
        $this->client_secret = $client_secret;
    }

    /**
     * @return null
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * @param null $user_id
     */
    public function setUserId($user_id)
    {
        $this->user_id = $user_id;
    }

    /**
     * @return null
     */
    public function getUserSecret()
    {
        return $this->user_secret;
    }

    /**
     * @param null $user_secret
     */
    public function setUserSecret($user_secret)
    {
        $this->user_secret = $user_secret;
    }


    public function setCommand(){
        $this->command = 'obtain_pat';
    }
    public function setParams()
    {
          $this->params =  array( "discovery_url"=>$this->getDiscoveryUrl(),
                                  "uma_discovery_url"=>$this->getUmaDiscoveryUrl(),
                                  "redirect_url"=>$this->getRedirectUrl(),
                                  "client_id"=>$this->getClientId(),
                                  "client_secret"=>$this->getClientSecret(),
                                  "user_id"=>$this->getUserId(),
                                  "user_secret"=>$this->getUserSecret()
          );
    }

}