<?php

class Register_client extends Client
{
    private $discoveryUrl = null;
    private $redirectUrl = null;
    private $clientName = null;
    private $register_client_app_type = null;
    private $register_client_response_types = null;
    private $register_client_grant_types = null;
    private $register_client_contacts = null;
    private $register_client_jwks_uri = null;
    private $register_client_token_endpoint_auth_method = null;


    public function __construct($protacol, $ip, $port)
    {
        parent::__construct($protacol, $ip, $port); // TODO: Change the autogenerated stub
    }
    /**
     * @return mixed
     */
    public function getDiscoveryUrl()
    {
        return $this->discoveryUrl;
    }

    /**
     * @param mixed $discoveryUrl
     */
    public function setDiscoveryUrl($discoveryUrl)
    {
        $this->discoveryUrl = $discoveryUrl;
    }

    /**
     * @return mixed
     */
    public function getRedirectUrl()
    {
        return $this->redirectUrl;
    }

    /**
     * @param mixed $redirectUrl
     */
    public function setRedirectUrl($redirectUrl)
    {
        $this->redirectUrl = $redirectUrl;
    }

    /**
     * @return mixed
     */
    public function getClientName()
    {
        return $this->clientName;
    }

    /**
     * @param mixed $clientName
     */
    public function setClientName($clientName)
    {
        $this->clientName = $clientName;
    }

    /**
     * @return mixed
     */
    public function getRegisterClientAppType()
    {
        return $this->register_client_app_type;
    }

    /**
     * @param mixed $register_client_app_type
     */
    public function setRegisterClientAppType($register_client_app_type)
    {
        $this->register_client_app_type = $register_client_app_type;
    }

    /**
     * @return mixed
     */
    public function getRegisterClientResponseTypes()
    {
        return $this->register_client_response_types;
    }

    /**
     * @param mixed $register_client_response_types
     */
    public function setRegisterClientResponseTypes($register_client_response_types)
    {
        $this->register_client_response_types = $register_client_response_types;
    }

    /**
     * @return mixed
     */
    public function getRegisterClientGrantTypes()
    {
        return $this->register_client_grant_types;
    }

    /**
     * @param mixed $register_client_grant_types
     */
    public function setRegisterClientGrantTypes($register_client_grant_types)
    {
        $this->register_client_grant_types = $register_client_grant_types;
    }

    /**
     * @return mixed
     */
    public function getRegisterClientContacts()
    {
        return $this->register_client_contacts;
    }

    /**
     * @param mixed $register_client_contacts
     */
    public function setRegisterClientContacts($register_client_contacts)
    {
        $this->register_client_contacts = $register_client_contacts;
    }

    /**
     * @return mixed
     */
    public function getRegisterClientJwksUri()
    {
        return $this->register_client_jwks_uri;
    }

    /**
     * @param mixed $register_client_jwks_uri
     */
    public function setRegisterClientJwksUri($register_client_jwks_uri)
    {
        $this->register_client_jwks_uri = $register_client_jwks_uri;
    }

    /**
     * @return mixed
     */
    public function getRegisterClientTokenEndpointAuthMethod()
    {
        return $this->register_client_token_endpoint_auth_method;
    }

    /**
     * @param mixed $register_client_token_endpoint_auth_method
     */
    public function setRegisterClientTokenEndpointAuthMethod($register_client_token_endpoint_auth_method)
    {
        $this->register_client_token_endpoint_auth_method = $register_client_token_endpoint_auth_method;
    }

    public function setCommand(){
        $this->command = 'register_client';
    }
    public function setParams()
    {
      $this->params = array( "discovery_url"=>$this->getDiscoveryUrl(),
          "redirect_url"=>$this->getRedirectUrl(),
          "client_name"=>$this->getClientName(),
          "response_types"=>$this->getRegisterClientResponseTypes(),
          "app_type"=>$this->getRegisterClientAppType(),
          "grant_types"=>$this->getRegisterClientGrantTypes(),
          "contacts"=>$this->getRegisterClientContacts(),
          "jwks_uri"=>$this->getRegisterClientJwksUri()
      );
    }

}