<?php

class Register_ticket extends Client
{
    private $uma_discovery_url = null;
    private $pat = null;
    private $am_host = null;
    private $rs_host = null;
    private $resource_set_id = null;
    private $scopes = array();
    private $request_http_method = null;
    private $request_url = null;
    /**
     * Register_ticket constructor.
     * @param $protacol='tcp', $ip='127.0.0.1', $port=8099
    **/
    public function __construct($protacol, $ip, $port)
    {
          parent::__construct($protacol, $ip, $port); // TODO: Change the autogenerated stub
    }

    /**
     * @return null
     */
    public function getUmaDiscoveryUrl()
    {
        return $this->uma_discovery_url;
    }

    /**
     * @param null $uma_discovery_url
     */
    public function setUmaDiscoveryUrl($uma_discovery_url)
    {
        $this->uma_discovery_url = $uma_discovery_url;
    }

    /**
     * @return null
     */
    public function getPat()
    {
        return $this->pat;
    }

    /**
     * @param null $pat
     */
    public function setPat($pat)
    {
        $this->pat = $pat;
    }

    /**
     * @return null
     */
    public function getAmHost()
    {
        return $this->am_host;
    }

    /**
     * @param null $am_host
     */
    public function setAmHost($am_host)
    {
        $this->am_host = $am_host;
    }

    /**
     * @return null
     */
    public function getRsHost()
    {
        return $this->rs_host;
    }

    /**
     * @param null $rs_host
     */
    public function setRsHost($rs_host)
    {
        $this->rs_host = $rs_host;
    }

    /**
     * @return null
     */
    public function getResourceSetId()
    {
        return $this->resource_set_id;
    }

    /**
     * @param null $resource_set_id
     */
    public function setResourceSetId($resource_set_id)
    {
        $this->resource_set_id = $resource_set_id;
    }

    /**
     * @return array
     */
    public function getScopes()
    {
        return $this->scopes;
    }

    /**
     * @param array $scopes
     */
    public function setScopes($scopes)
    {
        $this->scopes = $scopes;
    }

    /**
     * @return null
     */
    public function getRequestHttpMethod()
    {
        return $this->request_http_method;
    }

    /**
     * @param null $request_http_method
     */
    public function setRequestHttpMethod($request_http_method)
    {
        $this->request_http_method = $request_http_method;
    }

    /**
     * @return null
     */
    public function getRequestUrl()
    {
        return $this->request_url;
    }

    /**
     * @param null $request_url
     */
    public function setRequestUrl($request_url)
    {
        $this->request_url = $request_url;
    }


    public function setCommand(){
          $this->command = 'register_ticket';
    }
    public function setParams()
    {
          $this->params =  array( "uma_discovery_url"=>$this->getUmaDiscoveryUrl(),
                                  "pat"=>$this->getPat(),
                                  "am_host"=>$this->getAmHost(),
                                  "rs_host"=>$this->getRsHost(),
                                  "resource_set_id"=>$this->getResourceSetId(),
                                  "scopes"=>$this->getScopes(),
                                  "request_http_method"=>$this->getRequestHttpMethod(),
                                  "request_url"=>$this->getRequestUrl()
          );
    }

}