<?php
/**
 * Created by PhpStorm.
 * User: Vlad Karapetyan
 */
require_once 'Client_OXD.php';

class Register_resource extends Client_oxd
{
    /**start parameter for request!**/
        private $req_uma_discovery_url = null;
        private $req_pat = null;
        private $req_name = null;
        private $req_scopes = array();
    /**end request parameter**/

    /**start parameter for response!**/
        public static $resp_resource_status;
        public static $resp_id;
        public static $resp_rev;
    /**end response parameter**/


    public function __construct()
    {
        /**
         * Register_resource constructor.
         **/
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return null
     */
    public function getReqUmaDiscoveryUrl()
    {
        return $this->req_uma_discovery_url;
    }

    /**
     * @param null $req_uma_discovery_url
     */
    public function setReqUmaDiscoveryUrl($req_uma_discovery_url)
    {
        $this->req_uma_discovery_url = $req_uma_discovery_url;
    }

    /**
     * @return null
     */
    public function getReqPat()
    {
        return $this->req_pat;
    }

    /**
     * @param null $req_pat
     */
    public function setReqPat($req_pat)
    {
        $this->req_pat = $req_pat;
    }

    /**
     * @return null
     */
    public function getReqName()
    {
        return $this->req_name;
    }

    /**
     * @param null $name
     */
    public function setReqName($req_name)
    {
        $this->req_name = $req_name;
    }

    /**
     * @return array
     */
    public function getReqScopes()
    {
        return $this->req_scopes;
    }

    /**
     * @param array $req_scopes
     */
    public function setReqScopes($req_scopes)
    {
        $this->req_scopes = $req_scopes;
    }
    /*
     * @param static
    */
    public function setRespParam(){
        self::$resp_id = $this->getRespData()->_id;
        self::$resp_rev = $this->getRespData()->_rev;
        self::$resp_resource_status = $this->getRespData()->status;
    }

    public function setCommand()
    {
        $this->command = 'register_resource';
    }

    public function setParams()
    {
        $this->params = array(
            "uma_discovery_url" => $this->getReqUmaDiscoveryUrl(),
            "pat" => $this->getReqPat(),
            "name" => $this->getReqName(),
            "scopes" => $this->getReqScopes()
        );
    }

}