<?php
/**
 * Created by PhpStorm.
 * User: Vlad Karapetyan
 */
require_once 'Client_OXD.php';

class Register_site extends Client_oxd
{
    /**start parameter for request!**/
        private $req_authorization_redirect_uri = null;
        private $req_logout_redirect_uri = null;
        private $req_application_type = null;
        private $req_redirect_uris = null;
        private $req_acr_values = null;
        private $req_client_jwks_uri = null;
        private $req_client_token_endpoint_auth_method = null;
        private $req_client_req_uris = null;
        private $req_contacts = null;
    /**end request parameter**/

    /**start parameter for response!**/
        public static $resp_oxd_id;
    /**end response parameter**/

    public function __construct()
    {
        /**
         * req_access_token_status constructor.
         **/
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->setReqApplicationType();
    }

    /**
     * @return null
     */
    public function getReqLogoutRedirectUri()
    {
        return $this->req_logout_redirect_uri;
    }

    /**
     * @param null $req_logout_redirect_uri
     */
    public function setReqLogoutRedirectUri($req_logout_redirect_uri)
    {
        $this->req_logout_redirect_uri = $req_logout_redirect_uri;
    }

    /**
     * @return null
     */
    public function getReqClientJwksUri()
    {
        return $this->req_client_jwks_uri;
    }

    /**
     * @param null $req_client_jwks_uri
     */
    public function setReqClientJwksUri($req_client_jwks_uri)
    {
        $this->req_client_jwks_uri = $req_client_jwks_uri;
    }

    /**
     * @return null
     */
    public function getReqClientTokenEndpointAuthMethod()
    {
        return $this->req_client_token_endpoint_auth_method;
    }

    /**
     * @param null $req_client_token_endpoint_auth_method
     */
    public function setReqClientTokenEndpointAuthMethod($req_client_token_endpoint_auth_method)
    {
        $this->req_client_token_endpoint_auth_method = $req_client_token_endpoint_auth_method;
    }

    /**
     * @return null
     */
    public function getReqClientRequestUris()
    {
        return $this->req_client_req_uris;
    }

    /**
     * @param null $req_client_req_uris
     */
    public function setReqClientRequestUris($req_client_req_uris)
    {
        $this->req_client_req_uris = $req_client_req_uris;
    }

    /**
     * @return mixed
     */
    public function getReqApplicationType()
    {
        return $this->req_application_type;
    }

    /**
     * @param mixed $req_application_type
     */
    public function setReqApplicationType($req_application_type = 'web')
    {
        $this->req_application_type = $req_application_type;
    }

    /**
     * @return null
     */
    public function getReqAuthorizationRedirectUri()
    {
        return $this->req_authorization_redirect_uri;
    }

    /**
     * @param null $req_authorization_redirect_uri
     */
    public function setReqAuthorizationRedirectUri($req_authorization_redirect_uri)
    {
        $this->req_authorization_redirect_uri = $req_authorization_redirect_uri;
    }

    /**
     * @return null
     */
    public function getReqRedirectUris()
    {
        return $this->req_redirect_uris;
    }

    /**
     * @param null $req_redirect_uris
     */
    public function setReqRedirectUris($req_redirect_uris)
    {
        $this->req_redirect_uris = $req_redirect_uris;
    }

    /**
     * @return null
     */
    public function getReqAcrValues()
    {
        return $this->req_acr_values;
    }

    /**
     * @param null $req_acr_values
     */
    public function setReqAcrValues($req_acr_values = 'basic')
    {
        $this->req_acr_values = $req_acr_values;
    }

    /**
     * @return null
     */
    public function getReqContacts()
    {
        return $this->req_contacts;
    }

    /**
     * @param null $req_contacts
     */
    public function setReqContacts($req_contacts)
    {
        $this->req_contacts = $req_contacts;
    }
    /*
     * @param static
    */
    public function setRespParam(){
        self::$resp_oxd_id = $this->getRespData()->oxd_id;
    }

    public function setCommand()
    {
        $this->command = 'register_site';
    }

    public function setParams()
    {
        $this->params = array(
            "authorization_redirect_uri" => $this->getReqAuthorizationRedirectUri(),
            "logout_redirect_uri" => $this->getReqLogoutRedirectUri(),
            "application_type" => $this->getReqApplicationType(),
            "redirect_uris" => $this->getReqRedirectUris(),
            "acr_values" => $this->getReqAcrValues(),
            "client_jwks_uri" => $this->getReqClientJwksUri(),
            "client_token_endpoint_auth_method" => $this->getReqClientTokenEndpointAuthMethod(),
            "client_req_uris" => $this->getReqClientRequestUris(),
            "contacts" => $this->getReqContacts()
        );
    }

}