<?php

/**
 * Created by PhpStorm.
 * User: Vlad Karapetyan
 */
require_once 'Client_OXD.php';

class Register_client extends Client_oxd
{
    /**start parameter for request!**/
        private $req_discoveryUrl = null;
        private $req_redirectUrl = null;
        private $req_logout_redirect_url = null;
        private $req_client_name = null;
        private $req_resp_types = null;
        private $req_app_type = null;
        private $req_grant_types = null;
        private $req_contacts = null;
        private $req_jwks_uri = null;
    /**end request parameter**/

    /**start parameter for response!**/
        public static $resp_client_id;
        public static $resp_client_secret;
        public static $resp_registration_access_token;
        public static $resp_client_secret_expires_at;
        public static $resp_registration_client_uri;
        public static $resp_client_id_issued_at;
    /**end response parameter**/

    public function __construct()
    {
        /**
         * Register_client constructor.
         **/
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return null
     */
    public function getReqLogoutRedirectUrl()
    {
        return $this->req_logout_redirect_url;
    }

    /**
     * @param null $req_logout_redirect_url
     */
    public function setReqLogoutRedirectUrl($req_logout_redirect_url)
    {
        $this->req_logout_redirect_url = $req_logout_redirect_url;
    }

    /**
     * @return mixed
     */
    public function getReqDiscoveryUrl()
    {
        return $this->req_discoveryUrl;
    }

    /**
     * @param mixed $req_discoveryUrl
     */
    public function setReqDiscoveryUrl($req_discoveryUrl)
    {
        $this->req_discoveryUrl = $req_discoveryUrl;
    }

    /**
     * @return mixed
     */
    public function getReqRedirectUrl()
    {
        return $this->req_redirectUrl;
    }

    /**
     * @param mixed $req_redirectUrl
     */
    public function setReqRedirectUrl($req_redirectUrl)
    {
        $this->req_redirectUrl = $req_redirectUrl;
    }

    /**
     * @return mixed
     */
    public function getReqClientName()
    {
        return $this->req_client_name;
    }

    /**
     * @param mixed $req_client_name
     */
    public function setReqClientName($req_client_name)
    {
        $this->req_client_name = $req_client_name;
    }

    /**
     * @return mixed
     */
    public function getReqAppType()
    {
        return $this->req_app_type;
    }

    /**
     * @param mixed $req_app_type
     */
    public function setReqAppType($req_app_type)
    {
        $this->req_app_type = $req_app_type;
    }

    /**
     * @return mixed
     */
    public function getReqResponseTypes()
    {
        return $this->req_resp_types;
    }

    /**
     * @param mixed $req_resp_types
     */
    public function setReqResponseTypes($req_resp_types)
    {
        $this->req_resp_types = $req_resp_types;
    }

    /**
     * @return mixed
     */
    public function getReqGrantTypes()
    {
        return $this->req_grant_types;
    }

    /**
     * @param mixed $req_grant_types
     */
    public function setReqGrantTypes($req_grant_types)
    {
        $this->req_grant_types = $req_grant_types;
    }

    /**
     * @return mixed
     */
    public function getReqContacts()
    {
        return $this->req_contacts;
    }

    /**
     * @param mixed $req_contacts
     */
    public function setReqContacts($req_contacts)
    {
        $this->req_contacts = $req_contacts;
    }

    /**
     * @return mixed
     */
    public function getReqJwksUri()
    {
        return $this->req_jwks_uri;
    }

    /**
     * @param mixed $req_jwks_uri
     */
    public function setReqJwksUri($req_jwks_uri)
    {
        $this->req_jwks_uri = $req_jwks_uri;
    }
    /*
     * @param static
    */
    public function setRespParam(){
        self::$resp_client_id = $this->getRespData()->client_id;
        self::$resp_client_secret = $this->getRespData()->client_secret;
        self::$resp_registration_access_token = $this->getRespData()->registration_access_token;
        self::$resp_client_secret_expires_at = $this->getRespData()->client_secret_expires_at;
        self::$resp_registration_client_uri = $this->getRespData()->registration_client_uri;
        self::$resp_client_id_issued_at = $this->getRespData()->client_id_issued_at;
    }

    public function setCommand()
    {
        $this->command = 'register_client';
    }

    public function setParams()
    {
        $this->params = array(
            "discovery_url" => $this->getReqDiscoveryUrl(),
            "redirect_url" => $this->getReqRedirectUrl(),
            "logout_redirect_url" => $this->getReqLogoutRedirectUrl(),
            "client_name" => $this->getReqClientName(),
            "resp_types" => $this->getReqResponseTypes(),
            "app_type" => $this->getReqAppType(),
            "grant_types" => $this->getReqGrantTypes(),
            "contacts" => $this->getReqContacts(),
            "jwks_uri" => $this->getReqJwksUri()
        );
    }

}

