<?php

require_once 'Client.php';

class Register_resource extends Client
{
    /**start parameter for request!**/
    private $request_uma_discovery_url = null;
    private $request_pat = null;
    private $request_name = null;
    private $request_scopes = array();
    /**end request parameter**/

    /**start parameter for response!**/
    private $response_status;
    private $response_id;
    private $response_rev;

    /**end response parameter**/


    public function __construct()
    {
        /**
         * Register_resource constructor.
         * @param $ip='127.0.0.1', $port=8099
         **/
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return null
     */
    public function getRequestUmaDiscoveryUrl()
    {
        return $this->request_uma_discovery_url;
    }

    /**
     * @param null $request_uma_discovery_url
     */
    public function setRequestUmaDiscoveryUrl($request_uma_discovery_url)
    {
        $this->request_uma_discovery_url = $request_uma_discovery_url;
    }

    /**
     * @return null
     */
    public function getRequestPat()
    {
        return $this->request_pat;
    }

    /**
     * @param null $request_pat
     */
    public function setRequestPat($request_pat)
    {
        $this->request_pat = $request_pat;
    }

    /**
     * @return null
     */
    public function getRequestName()
    {
        return $this->request_name;
    }

    /**
     * @param null $name
     */
    public function setRequestName($request_name)
    {
        $this->request_name = $request_name;
    }

    /**
     * @return array
     */
    public function getRequestScopes()
    {
        return $this->request_scopes;
    }

    /**
     * @param array $request_scopes
     */
    public function setRequestScopes($request_scopes)
    {
        $this->request_scopes = $request_scopes;
    }

    /**
     * @return mixed
     */
    public function getResponseRev()
    {
        $this->response_rev = $this->getResponseData()->_rev;
        return $this->response_rev;
    }

    /**
     * @return mixed
     */
    public function getResponseStatus()
    {
        $this->response_status = $this->getResponseData()->status;

        return $this->response_status;
    }

    /**
     * @return mixed
     */
    public function getResponseId()
    {
        $this->response_id = $this->getResponseData()->_id;
        return $this->response_id;
    }


    public function setCommand()
    {
        $this->command = 'register_resource';
    }

    public function setParams()
    {
        $this->params = array(
            "uma_discovery_url" => $this->getRequestUmaDiscoveryUrl(),
            "pat" => $this->getRequestPat(),
            "name" => $this->getRequestName(),
            "scopes" => $this->getRequestScopes()
        );
    }

}