<?php

class Register_resource extends Client
{
    private $uma_discovery_url = null;
    private $pat = null;
    private $name = null;
    private $scopes = array();
    /**
     * Obtain_pat constructor.
     * @param $protacol='tcp', $ip='127.0.0.1', $port=8099
    **/
    public function __construct($protacol, $ip, $port)
    {
          parent::__construct($protacol, $ip, $port); // TODO: Change the autogenerated stub
    }

    /**
     * @return null
     */
    public function getUmaDiscoveryUrl()
    {
          return $this->uma_discovery_url;
    }

    /**
     * @param null $uma_discovery_url
     */
    public function setUmaDiscoveryUrl($uma_discovery_url)
    {
          $this->uma_discovery_url = $uma_discovery_url;
    }

    /**
     * @return null
     */
    public function getPat()
    {
          return $this->pat;
    }

    /**
     * @param null $pat
     */
    public function setPat($pat)
    {
          $this->pat = $pat;
    }

    /**
     * @return null
     */
    public function getName()
    {
          return $this->name;
    }

    /**
     * @param null $name
     */
    public function setName($name)
    {
          $this->name = $name;
    }

    /**
     * @return array
     */
    public function getScopes()
    {
          return $this->scopes;
    }

    /**
     * @param array $scopes
     */
    public function setScopes($scopes)
    {
          $this->scopes = $scopes;
    }



    public function setCommand(){
          $this->command = 'register_resource';
    }
    public function setParams()
    {
          $this->params =  array( "uma_discovery_url"=>$this->getUmaDiscoveryUrl(),
                                  "pat"=>$this->getPat(),
                                  "name"=>$this->getName(),
                                  "scopes"=>$this->getScopes()
          );
    }

}