<?php

require_once 'Client.php';

class Register_ticket extends Client
{
    /**start parameter for request!**/
    private $request_uma_discovery_url = null;
    private $request_pat = null;
    private $request_am_host = null;
    private $request_rs_host = null;
    private $request_resource_set_id = null;
    private $request_scopes = array();
    private $request_http_method = null;
    private $request_url = null;
    /**end request parameter**/

    /**start parameter for response!**/
    private $response_ticket;

    /**end response parameter**/

    public function __construct()
    {
        /**
         * Register_ticket constructor.
         * @param $ip='127.0.0.1', $port=8099
         **/
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getResponseTicket()
    {
        $this->response_ticket = $this->getResponseData()->ticket;
        return $this->response_ticket;
    }

    /**
     * @return null
     */
    public function getRequestUmaDiscoveryUrl()
    {
        return $this->request_uma_discovery_url;
    }

    /**
     * @param null $request_uma_discovery_url
     */
    public function setRequestUmaDiscoveryUrl($request_uma_discovery_url)
    {
        $this->request_uma_discovery_url = $request_uma_discovery_url;
    }

    /**
     * @return null
     */
    public function getRequestPat()
    {
        return $this->request_pat;
    }

    /**
     * @param null $request_pat
     */
    public function setRequestPat($request_pat)
    {
        $this->pat = $request_pat;
    }

    /**
     * @return null
     */
    public function getRequestAmHost()
    {
        return $this->request_am_host;
    }

    /**
     * @param null $am_host
     */
    public function setRequestAmHost($request_am_host)
    {
        $this->request_am_host = $request_am_host;
    }

    /**
     * @return null
     */
    public function getRequestRsHost()
    {
        return $this->request_rs_host;
    }

    /**
     * @param null $request_rs_host
     */
    public function setRequestRsHost($request_rs_host)
    {
        $this->request_rs_host = $request_rs_host;
    }

    /**
     * @return null
     */
    public function getRequestResourceSetId()
    {
        return $this->request_resource_set_id;
    }

    /**
     * @param null $resource_set_id
     */
    public function setRequestResourceSetId($request_resource_set_id)
    {
        $this->request_resource_set_id = $request_resource_set_id;
    }

    /**
     * @return array
     */
    public function getRequestScopes()
    {
        return $this->request_scopes;
    }

    /**
     * @param array $request_scopes
     */
    public function setRequestScopes($request_scopes)
    {
        $this->request_scopes = $request_scopes;
    }

    /**
     * @return null
     */
    public function getRequestHttpMethod()
    {
        return $this->request_http_method;
    }

    /**
     * @param null $request_http_method
     */
    public function setRequestHttpMethod($request_http_method)
    {
        $this->request_http_method = $request_http_method;
    }

    /**
     * @return null
     */
    public function getRequestUrl()
    {
        return $this->request_url;
    }

    /**
     * @param null $request_url
     */
    public function setRequestUrl($request_url)
    {
        $this->request_url = $request_url;
    }


    public function setCommand()
    {
        $this->command = 'register_ticket';
    }

    public function setParams()
    {
        $this->params = array(
            "uma_discovery_url" => $this->getRequestUmaDiscoveryUrl(),
            "pat" => $this->getRequestPat(),
            "am_host" => $this->getRequestAmHost(),
            "rs_host" => $this->getRequestRsHost(),
            "resource_set_id" => $this->getRequestResourceSetId(),
            "scopes" => $this->getRequestScopes(),
            "request_http_method" => $this->getRequestHttpMethod(),
            "request_url" => $this->getRequestUrl()
        );
    }

}