<?php

include 'Client.php';

class Register_site extends Client
{
    /**start parameter for request!**/
    private $request_application_type = null;
    private $request_authorization_redirect_uri = null;
    private $request_redirect_uris = null;
    private $request_acr_values = null;
    private $request_contacts = null;
    /**end request parameter**/

    /**start parameter for response!**/
    private $response_oxd_id;
    /**end response parameter**/

    public function __construct()
    {
        /**
         * request_access_token_status constructor.
         * @param  $protacol='tcp', $ip='127.0.0.1', $port=8099
         **/
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getRequestApplicationType()
    {
        return $this->request_application_type;
    }

    /**
     * @param mixed $request_application_type
     */
    public function setRequestApplicationType($request_application_type ='web')
    {
        $this->request_application_type = $request_application_type;
    }

    /**
     * @return null
     */
    public function getRequestAuthorizationRedirectUri()
    {
        return $this->request_authorization_redirect_uri;
    }

    /**
     * @param null $request_authorization_redirect_uri
     */
    public function setRequestAuthorizationRedirectUri($request_authorization_redirect_uri)
    {
        $this->request_authorization_redirect_uri = $request_authorization_redirect_uri;
    }

    /**
     * @return null
     */
    public function getRequestRedirectUris()
    {
        return $this->request_redirect_uris;
    }

    /**
     * @param null $request_redirect_uris
     */
    public function setRequestRedirectUris($request_redirect_uris)
    {
        $this->request_redirect_uris = $request_redirect_uris;
    }

    /**
     * @return null
     */
    public function getRequestAcrValues()
    {
        return $this->request_acr_values;
    }

    /**
     * @param null $request_acr_values
     */
    public function setRequestAcrValues($request_acr_values)
    {
        $this->request_acr_values = $request_acr_values;
    }

    /**
     * @return null
     */
    public function getRequestContacts()
    {
        return $this->request_contacts;
    }

    /**
     * @param null $request_contacts
     */
    public function setRequestContacts($request_contacts)
    {
        $this->request_contacts = $request_contacts;
    }

    /**
     * @return mixed
     */
    public function getResponseOxdId()
    {
        $this->response_oxd_id = $this->getResponseData()->oxd_id;
        return $this->response_oxd_id;
    }

    /**
     * @param mixed $response_oxd_id
     */
    public function setResponseOxdId($response_oxd_id)
    {
        $this->response_oxd_id = $response_oxd_id;
    }

    public function setCommand(){
          $this->command = 'register_site';
    }

    public function setParams()
    {
          $this->params =  array( "application_type" => $this->getRequestApplicationType(),
                                  "authorization_redirect_uri" => $this->getRequestAuthorizationRedirectUri(),
                                  "redirect_uris" => $this->getRequestRedirectUris(),
                                  "acr_values" => $this->getRequestAcrValues(),
                                  "contacts" => $this->getRequestContacts()
          );
    }

}