<?php
/**
 * Created by PhpStorm.
 * User: Vlad Karapetyan
 */
require_once 'Client_OXD.php';

class Register_ticket extends Client_oxd
{
    /**start parameter for request!**/
        private $req_uma_discovery_url = null;
        private $req_pat = null;
        private $req_am_host = null;
        private $req_rs_host = null;
        private $req_resource_set_id = null;
        private $req_scopes = array();
        private $req_http_method = null;
        private $req_url = null;
    /**end request parameter**/

    /**start parameter for response!**/
        public static $resp_ticket;
    /**end response parameter**/

    public function __construct()
    {
        /**
         * Register_ticket constructor.
         **/
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    /*
     * @param static
    */
    public function setRespParam(){
        self::$resp_ticket = $this->getRespData()->ticket;
    }

    /**
     * @return null
     */
    public function getReqUmaDiscoveryUrl()
    {
        return $this->req_uma_discovery_url;
    }

    /**
     * @param null $req_uma_discovery_url
     */
    public function setReqUmaDiscoveryUrl($req_uma_discovery_url)
    {
        $this->req_uma_discovery_url = $req_uma_discovery_url;
    }

    /**
     * @return null
     */
    public function getReqPat()
    {
        return $this->req_pat;
    }

    /**
     * @param null $req_pat
     */
    public function setReqPat($req_pat)
    {
        $this->pat = $req_pat;
    }

    /**
     * @return null
     */
    public function getReqAmHost()
    {
        return $this->req_am_host;
    }

    /**
     * @param null $am_host
     */
    public function setReqAmHost($req_am_host)
    {
        $this->req_am_host = $req_am_host;
    }

    /**
     * @return null
     */
    public function getReqRsHost()
    {
        return $this->req_rs_host;
    }

    /**
     * @param null $req_rs_host
     */
    public function setReqRsHost($req_rs_host)
    {
        $this->req_rs_host = $req_rs_host;
    }

    /**
     * @return null
     */
    public function getReqResourceSetId()
    {
        return $this->req_resource_set_id;
    }

    /**
     * @param null $resource_set_id
     */
    public function setReqResourceSetId($req_resource_set_id)
    {
        $this->req_resource_set_id = $req_resource_set_id;
    }

    /**
     * @return array
     */
    public function getReqScopes()
    {
        return $this->req_scopes;
    }

    /**
     * @param array $req_scopes
     */
    public function setReqScopes($req_scopes)
    {
        $this->req_scopes = $req_scopes;
    }

    /**
     * @return null
     */
    public function getReqHttpMethod()
    {
        return $this->req_http_method;
    }

    /**
     * @param null $req_http_method
     */
    public function setReqHttpMethod($req_http_method)
    {
        $this->req_http_method = $req_http_method;
    }

    /**
     * @return null
     */
    public function getReqUrl()
    {
        return $this->req_url;
    }

    /**
     * @param null $req_url
     */
    public function setReqUrl($req_url)
    {
        $this->req_url = $req_url;
    }


    public function setCommand()
    {
        $this->command = 'register_ticket';
    }

    public function setParams()
    {
        $this->params = array(
            "uma_discovery_url" => $this->getReqUmaDiscoveryUrl(),
            "pat" => $this->getReqPat(),
            "am_host" => $this->getReqAmHost(),
            "rs_host" => $this->getReqRsHost(),
            "resource_set_id" => $this->getReqResourceSetId(),
            "scopes" => $this->getReqScopes(),
            "req_http_method" => $this->getReqHttpMethod(),
            "req_url" => $this->getReqUrl()
        );
    }

}