<?php

class Rpt_status extends Client
{
    private $uma_discovery_url = null;
    private $pat = null;
    private $rpt = null;

    /**
     * Rpt_status constructor.
     * @param $protacol='tcp', $ip='127.0.0.1', $port=8099
    **/
    public function __construct($protacol, $ip, $port)
    {
          parent::__construct($protacol, $ip, $port); // TODO: Change the autogenerated stub
    }

    /**
     * @return null
     */
    public function getUmaDiscoveryUrl()
    {
        return $this->uma_discovery_url;
    }

    /**
     * @param null $uma_discovery_url
     */
    public function setUmaDiscoveryUrl($uma_discovery_url)
    {
        $this->uma_discovery_url = $uma_discovery_url;
    }

    /**
     * @return null
     */
    public function getPat()
    {
        return $this->pat;
    }

    /**
     * @param null $pat
     */
    public function setPat($pat)
    {
        $this->pat = $pat;
    }

    /**
     * @return null
     */
    public function getRpt()
    {
        return $this->rpt;
    }

    /**
     * @param null $rpt
     */
    public function setRpt($rpt)
    {
        $this->rpt = $rpt;
    }


    public function setCommand(){
          $this->command = 'rpt_status';
    }
    public function setParams()
    {
          $this->params =  array( "uma_discovery_url"=>$this->getUmaDiscoveryUrl(),
                                  "pat"=>$this->getPat(),
                                  "rpt"=>$this->getRpt()
          );
    }

}