<?php
/**
 * Created by PhpStorm.
 * User: Vlad Karapetyan
 */
require_once 'Client_OXD.php';

class Rpt_status extends Client_oxd
{
    /**start parameter for request!**/
        private $req_uma_discovery_url = null;
        private $req_pat = null;
        private $req_rpt = null;
    /**end request parameter**/

    /**start parameter for response!**/
        public static $resp_active;
        public static $resp_expires_at;
        public static $resp_issued_at;
        public static $resp_permissions;
        public static $resp_permissions_scopes;
        public static $resp_permissions_resource_set_id;
        public static $resp_permissions_expires_at;
    /**end response parameter**/


    public function __construct()
    {
        /**
         * Rpt_status constructor.
         **/
        parent::__construct(); // TODO: Change the autogenerated stub
    }
    /**
     * @return null
     */
    public function getReqUmaDiscoveryUrl()
    {
        return $this->req_uma_discovery_url;
    }
    /*
     * @param static
    */
    public function setRespParam(){
        self::$resp_active = $this->getRespData()->active;
        self::$resp_expires_at = $this->getRespData()->expires_at;
        self::$resp_issued_at = $this->getRespData()->issued_at;
        self::$resp_permissions = $this->getRespData()->permissions;
        self::$resp_permissions_scopes = self::$resp_permissions->scopes;
        self::$resp_permissions_expires_at = self::$resp_permissions->expires_at;
        self::$resp_permissions_resource_set_id = self::$resp_permissions->resource_set_id;
    }
    /**
     * @param null $req_uma_discovery_url
     */
    public function setReqUmaDiscoveryUrl($req_uma_discovery_url)
    {
        $this->req_uma_discovery_url = $req_uma_discovery_url;
    }

    /**
     * @return null
     */
    public function getReqPat()
    {
        return $this->req_pat;
    }

    /**
     * @param null $req_pat
     */
    public function setReqPat($req_pat)
    {
        $this->req_pat = $req_pat;
    }

    /**
     * @return null
     */
    public function getReqRpt()
    {
        return $this->req_rpt;
    }

    /**
     * @param null $req_rpt
     */
    public function setReqRpt($req_rpt)
    {
        $this->rpt = $req_rpt;
    }


    public function setCommand()
    {
        $this->command = 'rpt_status';
    }

    public function setParams()
    {
        $this->params = array(
            "uma_discovery_url" => $this->getReqUmaDiscoveryUrl(),
            "pat" => $this->getReqPat(),
            "rpt" => $this->getReqRpt()
        );
    }

}