<?php

include 'Client.php';

class Rpt_status extends Client
{
    /**start parameter for request!**/
    private $request_uma_discovery_url = null;
    private $request_pat = null;
    private $request_rpt = null;
    /**end request parameter**/

    /**start parameter for response!**/
    private $response_active;
    private $response_expires_at;
    private $response_issued_at;
    private $response_permissions;
    /**end response parameter**/


    public function __construct()
    {
        /**
         * Rpt_status constructor.
         * @param $protacol='tcp', $ip='127.0.0.1', $port=8099
        **/
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return null
     */
    public function getRequestUmaDiscoveryUrl()
    {
        return $this->request_uma_discovery_url;
    }

    /**
     * @return mixed
     */
    public function getResponseActive()
    {
        $this->response_active = $this->getResponseData()->active;
        return $this->response_active;
    }

    /**
     * @return mixed
     */
    public function getResponseExpiresAt()
    {
        $this->response_expires_at = $this->getResponseData()->expires_at;
        return $this->response_expires_at;
    }

    /**
     * @return mixed
     */
    public function getResponseIssuedAt()
    {
        $this->response_issued_at = $this->getResponseData()->issued_at;
        return $this->response_issued_at;
    }

    /**
     * @return mixed
     */
    public function getResponsePermissions()
    {
        $this->response_permissions = $this->getResponseData()->permissions;
        return $this->response_permissions;
    }

    /**
     * @param null $request_uma_discovery_url
     */
    public function setRequestUmaDiscoveryUrl($request_uma_discovery_url)
    {
        $this->request_uma_discovery_url = $request_uma_discovery_url;
    }

    /**
     * @return null
     */
    public function getRequestPat()
    {
        return $this->request_pat;
    }

    /**
     * @param null $request_pat
     */
    public function setRequestPat($request_pat)
    {
        $this->request_pat = $request_pat;
    }

    /**
     * @return null
     */
    public function getRequestRpt()
    {
        return $this->request_rpt;
    }

    /**
     * @param null $request_rpt
     */
    public function setRequestRpt($request_rpt)
    {
        $this->rpt = $request_rpt;
    }


    public function setCommand(){
          $this->command = 'rpt_status';
    }
    public function setParams()
    {
          $this->params =  array( "uma_discovery_url"=>$this->getRequestUmaDiscoveryUrl(),
                                  "pat"=>$this->getRequestPat(),
                                  "rpt"=>$this->getRequestRpt()
          );
    }

}