<?php
/**
 * Created Vlad Karapetyan
 */

require_once 'Client_OXD_RP.php';

class Get_authorization_code extends Client_OXD_RP
{
    /**start parameter for request!**/
        private $request_username = null;
        private $request_password = null;
        private $request_oxd_id = null;
        private $request_acr_values = null;
    /**end request parameter**/

    /**start parameter for response!**/
        private $response_code;
    /**end response parameter**/

    public function __construct($base_url)
    {
        /**
         * request_access_token_status constructor.
         **/
        parent::__construct($base_url); // TODO: Change the autogenerated stub
    }

    /**
     * @param mixed $request_username
     */
    public function setRequestUsername($request_username)
    {
        $this->request_username = $request_username;
    }

    /**
     * @param null $request_password
     */
    public function setRequestPassword($request_password)
    {
        $this->request_password = $request_password;
    }

    /**
     * @param null $request_oxd_id
     */
    public function setRequestOxdId($request_oxd_id)
    {
        $this->request_oxd_id = $request_oxd_id;
    }

    /**
     * @param null $request_acr_values
     */
    public function setRequestAcrValues($request_acr_values)
    {
        $this->request_acr_values = $request_acr_values;
    }

    /**
     * @return null
     */
    public function getRequestAcrValues()
    {
        return $this->request_acr_values;
    }

    /**
     * @return mixed
     */
    public function getRequestUsername()
    {
        return $this->request_username;
    }

    /**
     * @return null
     */
    public function getRequestPassword()
    {
        return $this->request_password;
    }

    /**
     * @return null
     */
    public function getRequestOxdId()
    {
        return $this->request_oxd_id;
    }

    /**
     * @return mixed
     */
    public function getResponseCode()
    {
        return $this->response_code;
    }



    public function setCommand()
    {
        $this->command = 'get_authorization_code';
    }

    public function setParams()
    {
        $this->params = array(
            "username" => $this->getRequestUsername(),
            "password" => $this->getRequestPassword(),
            "oxd_id" => $this->getRequestOxdId(),
            "acr_values" => $this->getRequestAcrValues()
        );
    }

}