<?php

/**
 * Created by PhpStorm.
 * User: Vlad-Home
 * Date: 5/3/2016
 * Time: 12:57 PM
 */
require_once 'Client_OXD_RP.php';

class Uma_rp_get_rpt extends Client_OXD_RP{
    /**start parameter for request!**/
    private $request_oxd_id = null;
    private $request_force_new = null;
    /**end request parameter**/

    /**start parameter for response!**/
    private $response_rpt;
    /**end response parameter**/

    public function __construct($base_url='./')
    {
        parent::__construct($base_url); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getRequestOxdId()
    {
        return $this->request_oxd_id;
    }

    /**
     * @param mixed $request_oxd_id
     */
    public function setRequestOxdId($request_oxd_id)
    {
        $this->request_oxd_id = $request_oxd_id;
    }

    /**
     * @return null
     */
    public function getRequestForceNew()
    {
        return $this->request_force_new;
    }

    /**
     * @param null $request_force_new
     */
    public function setRequestForceNew($request_force_new)
    {
        $this->request_force_new = $request_force_new;
    }

    /**
     * @return mixed
     */
    public function getResponseRpt()
    {
        $this->response_rpt = $this->getResponseData()->rpt;
        return $this->response_rpt;
    }


    public function setCommand()
    {
        $this->command = 'uma_rp_get_rpt';
    }

    public function setParams()
    {
        $this->params = array(
            "oxd_id" => $this->getRequestOxdId(),
            "force_new" => $this->getRequestForceNew()

        );
    }

}