<?php

/**
 * Created by PhpStorm.
 * User: Vlad-Home
 * Date: 5/3/2016
 * Time: 12:57 PM
 */
require_once 'Client_OXD_RP.php';

class Uma_rp_authorize_rpt extends Client_OXD_RP{
    /**start parameter for request!**/
    private $request_oxd_id = null;
    private $request_rpt = null;
    private $request_ticket = null;
    /**end request parameter**/

    public function __construct($base_url='./')
    {
        parent::__construct($base_url); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getRequestOxdId()
    {
        return $this->request_oxd_id;
    }

    /**
     * @param mixed $request_oxd_id
     */
    public function setRequestOxdId($request_oxd_id)
    {
        $this->request_oxd_id = $request_oxd_id;
    }

    /**
     * @return null
     */
    public function getRequestRpt()
    {
        return $this->request_rpt;
    }

    /**
     * @param null $request_rpt
     */
    public function setRequestRpt($request_rpt)
    {
        $this->request_rpt = $request_rpt;
    }

    /**
     * @return null
     */
    public function getRequestTicket()
    {
        return $this->request_ticket;
    }

    /**
     * @param null $request_ticket
     */
    public function setRequestTicket($request_ticket)
    {
        $this->request_ticket = $request_ticket;
    }


    public function setCommand()
    {
        $this->command = 'uma_rp_authorize_rpt';
    }

    public function setParams()
    {
        $this->params = array(
            "oxd_id" => $this->getRequestOxdId(),
            "rpt" => $this->getRequestRpt(),
            "ticket" => $this->getRequestTicket()
        );
    }

}