<?php

/**
 * Created by PhpStorm.
 * User: Vlad-Home
 * Date: 5/3/2016
 * Time: 12:57 PM
 */
require_once 'Client_OXD_RP.php';

class Uma_rp_get_gat extends Client_OXD_RP{
    /**start parameter for request!**/
    private $request_oxd_id = null;
    private $request_scopes = null;
    /**end request parameter**/

    /**start parameter for response!**/
    private $response_gat;
    /**end response parameter**/

    public function __construct($base_url='./')
    {
        parent::__construct($base_url); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getRequestOxdId()
    {
        return $this->request_oxd_id;
    }

    /**
     * @param mixed $request_oxd_id
     */
    public function setRequestOxdId($request_oxd_id)
    {
        $this->request_oxd_id = $request_oxd_id;
    }

    /**
     * @return null
     */
    public function getRequestScopes()
    {
        return $this->request_scopes;
    }

    /**
     * @param null $request_scopes
     */
    public function setRequestScopes(array $request_scopes)
    {
        $this->request_scopes = $request_scopes;
    }

    /**
     * @return mixed
     */
    public function getResponseGat()
    {
        return $this->response_gat;
    }

    public function setCommand()
    {
        $this->command = 'uma_rp_get_gat';
    }

    public function setParams()
    {
        $this->params = array(
            "oxd_id" => $this->getRequestOxdId(),
            "scopes" => $this->getRequestScopes()

        );
    }

}