<?php

/**
 * Created by PhpStorm.
 * User: Vlad-Home
 * Date: 5/3/2016
 * Time: 12:57 PM
 */
require_once 'Client_OXD_RP.php';

class Uma_rs_protect extends Client_OXD_RP{
    /**start parameter for request!**/
    private $request_oxd_id = null;
    private $request_resources = null;
    /**end request parameter**/

    public function __construct($base_url='./')
    {
        parent::__construct($base_url); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getRequestOxdId()
    {
        return $this->request_oxd_id;
    }

    /**
     * @param mixed $request_oxd_id
     */
    public function setRequestOxdId($request_oxd_id)
    {
        $this->request_oxd_id = $request_oxd_id;
    }

    /**
     * @return null
     */
    public function getRequestResources()
    {
        return $this->request_resources;
    }

    /**
     * @param null $request_resources
     */
    public function setRequestResources(array $request_resources)
    {
        $this->request_resources = $request_resources;
    }


    public function setCommand()
    {
        $this->command = 'uma_rs_protect';
    }

    public function setParams()
    {
        $this->params = array(
            "oxd_id" => $this->getRequestOxdId(),
            "resources" => $this->getRequestResources()

        );
    }

}